export { default as Main } from "./main"
export { default as Calculator } from "./calculator"
export { default as TableCrud } from "./tablecrud"
export { default as UpAndDown } from "./upanddown"
export { default as TodoList } from "./todolist"